package com.crudetech.tictactoe.client.swing;

/**
 *
 */
public class TicTacToeGameForm extends javax.swing.JFrame {

    /** Creates new form TicTacToeGameForm */
    public TicTacToeGameForm() {
        setTitle("Tic Tac Toe (c) 2011 Andreas Mueller");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticTacToesGridPane = new javax.swing.JScrollPane();
        jTicTacToeGrid1 = new com.crudetech.tictactoe.client.swing.grid.JTicTacToeGrid();
        mainMenu = new javax.swing.JMenuBar();
        javax.swing.JMenu gameMenu = new javax.swing.JMenu();
        newSimpleGameMenu = new javax.swing.JMenuItem();
        newAdvancedGameMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jTicTacToeGrid1Layout = new javax.swing.GroupLayout(jTicTacToeGrid1);
        jTicTacToeGrid1.setLayout(jTicTacToeGrid1Layout);
        jTicTacToeGrid1Layout.setHorizontalGroup(
            jTicTacToeGrid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );
        jTicTacToeGrid1Layout.setVerticalGroup(
            jTicTacToeGrid1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        ticTacToesGridPane.setViewportView(jTicTacToeGrid1);

        gameMenu.setText("Game");

        newSimpleGameMenu.setText("New Simple Game");
        newSimpleGameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSimpleGameMenuActionPerformed(evt);
            }
        });
        gameMenu.add(newSimpleGameMenu);

        newAdvancedGameMenu.setText("New Andvanced Game");
        newAdvancedGameMenu.setToolTipText("");
        gameMenu.add(newAdvancedGameMenu);

        mainMenu.add(gameMenu);

        editMenu.setText("Edit");
        mainMenu.add(editMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticTacToesGridPane, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ticTacToesGridPane, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void newSimpleGameMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSimpleGameMenuActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_newSimpleGameMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TicTacToeGameForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private com.crudetech.tictactoe.client.swing.grid.JTicTacToeGrid jTicTacToeGrid1;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem newAdvancedGameMenu;
    private javax.swing.JMenuItem newSimpleGameMenu;
    private javax.swing.JScrollPane ticTacToesGridPane;
    // End of variables declaration//GEN-END:variables
}
